@HOST_NAME = http://localhost:4000

### Get Tending Movies
GET {{HOST_NAME}}/api/v1/tmdb/getTrendingMovies

### Get Trending Tv shows
GET {{HOST_NAME}}/api/v1/tmdb/getTrendingTvShows

### Get Upcoming Movies
GET {{HOST_NAME}}/api/v1/tmdb/getUpcomingMovies